# Generated by Django 4.2.5 on 2023-09-14 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Berries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('snack', models.CharField(choices=[('O', 'Oran Berry'), ('C', 'Cheri Berry'), ('P', 'Pecha Berry'), ('R', 'Rawst Berry'), ('I', 'Iapapa Berry')], default='O', max_length=1)),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.pokemon')),
            ],
        ),
    ]
