# Generated by Django 4.2.5 on 2023-09-14 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_berries'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=25)),
            ],
        ),
        migrations.AlterModelOptions(
            name='berries',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='berries',
            name='date',
            field=models.DateField(verbose_name='Snack Date'),
        ),
    ]
