# Generated by Django 4.2.5 on 2023-09-14 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_item_alter_berries_options_alter_berries_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='items',
            field=models.ManyToManyField(to='main_app.item'),
        ),
    ]
